Repository Team-HMH/HMH_iOS, pull requests merged in 2024-11, with the labels that each got.

#99 Refactor [#95] OAuthService 리펙토링
  HMH_Tuist_iOS/HMH-Tuist-iOS.xcworkspace/xcshareddata/xcschemes/HMH-Tuist-iOS-Workspace.xcscheme
  HMH_Tuist_iOS/Projects/Data/Demo/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  HMH_Tuist_iOS/Projects/Data/Demo/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  HMH_Tuist_iOS/Projects/Data/Demo/Resources/Assets.xcassets/Contents.json
  HMH_Tuist_iOS/Projects/Data/Derived/InfoPlists/DataDemo-Info.plist
  HMH_Tuist_iOS/Projects/Data/Derived/Sources/TuistAssets+DataDemo.swift
  HMH_Tuist_iOS/Projects/Data/Derived/Sources/TuistBundle+DataDemo.swift
  HMH_Tuist_iOS/Projects/Data/Project.swift
  HMH_Tuist_iOS/Projects/Data/Sources/Factory/OAuthServiceFactory.swift
  HMH_Tuist_iOS/Projects/Data/Sources/Repository/AuthRepository.swift
  HMH_Tuist_iOS/Projects/Data/Sources/Test/DataTestApp.swift
  HMH_Tuist_iOS/Projects/Data/Sources/Test/NetworkTestUI.swift
  HMH_Tuist_iOS/Projects/Data/Sources/Transform/Challenge/ChallengeDetailMapper.swift
  HMH_Tuist_iOS/Projects/Data/Sources/Transform/Point/PointDetailMapper.swift
  HMH_Tuist_iOS/Projects/Domain/Sources/Entity/Auth/OAuthProviderType.swift
  HMH_Tuist_iOS/Projects/Domain/Sources/RepositoryInterface/AuthRepositoryType.swift
  HMH_Tuist_iOS/Projects/Features/ChallengeFeature/Sources/ViewModels/ChallengeViewModel.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/DTO/Auth/AppInfoDTO.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/DTO/Auth/Request/SignUpRequestDTO.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Base/BaseService.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Builder/RequestHandler.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Config/APIHeaders.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Foundation/ErrorHandler.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Foundation/HMHNetworkError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/HMHNetworkError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/AuthError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/DecodeError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/RequestError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/ResponseError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Service/Auth/AuthAPI.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Service/OAuth/Apple/Manager/ASAuthorizationControllerProxy.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Service/OAuth/Apple/Manager/AppleLoginManager.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Service/OAuth/Apple/OAuthAppleService.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Service/OAuth/Foundation/OAuthProviderType.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Service/OAuth/Foundation/OAuthSerivce.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Service/OAuth/Kakao/OAuthKakoService.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/Service/AuthServiceTests.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/Service/PointServiceTests.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/Service/UserServiceTests.swift
  HMH_Tuist_iOS/Tuist/ProjectDescriptionHelpers/SourceFiles+Template.swift
  HMH_Tuist_iOS/graph.png
Labels: 🌿 REFACTOR, 🍀희재

#89 Fix [#88] 온보딩&포인트 QA 반영
  HMH_iOS/HMH_iOS/Global/Resource/String.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ChallengeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/PointView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Custom/ContentView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Navigation/NavigationBarView.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/AppGoalTimeView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingContentView.swift
Labels: 😎선우, 🔧FIX

#106 Refactor [#105] HMHNetworkErrorMapper 구현하기
  HMH_Tuist_iOS/Projects/Data/Sources/Test/DataTestApp.swift
  HMH_Tuist_iOS/Projects/Data/Sources/Test/NetworkTestUI.swift
  HMH_Tuist_iOS/Projects/Data/Tests/Sources/AuthRepositoryTests/Base/MockOAuthServiceFactory.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Base/BaseService.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Base/NetworkLogHandler.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Interceptor/TokenInterceptor.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Builder/Protocol/RequestHandling.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Builder/RequestHandler.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Foundation/ErrorHandler.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Foundation/HMHNetworkError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/ResponseError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/Service/AuthServiceTests.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/Service/ChallengeServiceTests.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/Service/PointServiceTests.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/Service/UserServiceTests.swift
  HMH_Tuist_iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
Labels: ✨FEAT, 🌿 REFACTOR, 🍀희재

#109 Test [#107] 네트워크 모듈 테스트 코드 작성하기 (Request)
  HMH_Tuist_iOS/Projects/Data/Tests/Sources/MockNetworkError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Base/Config.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Base/NetworkLogHandler.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Builder/RequestHandler.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Builder/URLRequestTargetType.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Builder/URLValidator.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Config/Task.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Encoders/JSONEncoding.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Encoders/ParameterEncodable.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Encoders/ParameterEncoding.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Encoders/RequestDataValidator.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Encoders/URLEncoding.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Foundation/HMHNetworkError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/AuthrizationError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/DecodeError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/RequestError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/RequestError/ParameterEncodingError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/RequestError/RequestError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/RequestError/URLValidationError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/ResponseError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/Mock/MockRequestHandler.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/Mock/MockTargetType.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/MockData/EncodableParameterMockData.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/MockData/ParameterMockData.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/MockData/URLRequestMockData.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/MockData/URLValidatorMockData.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/ParameterEncoderTest/JSONEncodingTest.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/ParameterEncoderTest/RequestDataValidatorTest.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/ParameterEncoderTest/RequestTestHandler.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/ParameterEncoderTest/URLEncodingTest.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/URLRequestTargetTypeTest/RequestHandlerTest.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/URLRequestTargetTypeTest/TaskTest.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/URLRequestTargetTypeTest/URLRequestTargetTypeTest.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/URLRequestTargetTypeTest/URLValidatorTest.swift
Labels: 🍀희재, 🪄 Test

#108 Refactor [#91] LoginFeature 리펙토링
  HMH_Tuist_iOS/Projects/App/Derived/InfoPlists/HMH-iOS-Info.plist
  HMH_Tuist_iOS/Projects/App/Sources/Common/Custom/SplashView.swift
  HMH_Tuist_iOS/Projects/Domain/Sources/Entity/Auth/OAuthProviderType.swift
  HMH_Tuist_iOS/Projects/Features/LoginFeature/Sources/LoginUseCase.swift
  HMH_Tuist_iOS/Projects/Features/LoginFeature/Sources/LoginView.swift
  HMH_Tuist_iOS/Projects/Features/LoginFeature/Sources/ViewModels/LoginViewModel.swift
  HMH_Tuist_iOS/Projects/Features/LoginFeature/Sources/Views/LoginButton.swift
  HMH_Tuist_iOS/Projects/Features/LoginFeature/Sources/Views/SwipeView.swift
Labels: 😎선우, 🌿 REFACTOR

#117 [Refactor] #116 Test/Release Config 분리 및 Tuist 세팅코드 리펙토링
  HMH_Tuist_iOS/HMH-Tuist-iOS.xcworkspace/xcshareddata/xcschemes/HMH-Tuist-iOS-Workspace.xcscheme
  HMH_Tuist_iOS/Plugins/ConfigPlugin/ProjectDescriptionHelpers/Configurations.swift
  HMH_Tuist_iOS/Plugins/EnvPlugin/ProjectDescriptionHelpers/SettingDictionary+.swift
  HMH_Tuist_iOS/Projects/Data/Sources/Test/DataTestApp.swift
  HMH_Tuist_iOS/Projects/Data/Tests/Sources/MockNetworkError.swift
  HMH_Tuist_iOS/Projects/Features/BaseFeatureDependency/Project.swift
  HMH_Tuist_iOS/Projects/Features/ChallengeFeature/Derived/InfoPlists/ChallengeFeatureInterface-Info.plist
  HMH_Tuist_iOS/Projects/Features/ChallengeFeature/Project.swift
  HMH_Tuist_iOS/Projects/Features/HomeFeature/Derived/InfoPlists/HomeFeatureInterface-Info.plist
  HMH_Tuist_iOS/Projects/Features/HomeFeature/Project.swift
  HMH_Tuist_iOS/Projects/Features/LoginFeature/Derived/InfoPlists/LoginFeatureInterface-Info.plist
  HMH_Tuist_iOS/Projects/Features/LoginFeature/Project.swift
  HMH_Tuist_iOS/Projects/Features/MyPageFeature/Derived/InfoPlists/MyPageFeatureInterface-Info.plist
  HMH_Tuist_iOS/Projects/Features/MyPageFeature/Project.swift
  HMH_Tuist_iOS/Projects/Features/OnboardingFeature/Derived/InfoPlists/OnboardingFeatureInterface-Info.plist
  HMH_Tuist_iOS/Projects/Features/OnboardingFeature/Project.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Base/BaseService.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Base/Config.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Base/NetworkLogHandler.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Interceptor/TokenInterceptor.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Builder/RequestHandler.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Builder/URLRequestTargetType.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Request/Config/Task.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Foundation/ErrorHandler.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/DecodeError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/RequestError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Foundation/Response/Error/Type/ResponseError.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/MockData/MockResult.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/MockData/NetworkResponseMockData.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/RequestTest/MockData/URLTargetTypeMockData.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/ResponseTest/ErrorHandlerTest.swift
  HMH_Tuist_iOS/Tuist/Dependencies.swift
  HMH_Tuist_iOS/Tuist/ProjectDescriptionHelpers/FeatureTargets.swift
  HMH_Tuist_iOS/Tuist/ProjectDescriptionHelpers/InfoPlist+Templates.swift
  HMH_Tuist_iOS/Tuist/ProjectDescriptionHelpers/Project+Templates.swift
  HMH_Tuist_iOS/Tuist/ProjectDescriptionHelpers/Scheme+Template.swift
  HMH_Tuist_iOS/Tuist/ProjectDescriptionHelpers/Target+Templates.swift
  HMH_Tuist_iOS/graph.png
Labels: ✨FEAT, 🌿 REFACTOR, 🍀희재

#103 Refactor [#97] 챌린지 모듈 리팩토링
  HMH_Tuist_iOS/Projects/Core/Sources/Extension/Date+.swift
  HMH_Tuist_iOS/Projects/Data/Sources/Mapper/Challenge/ChallengeSuccessInfoMapper.swift
  HMH_Tuist_iOS/Projects/Data/Sources/Repository/ChallengeRepository.swift
  HMH_Tuist_iOS/Projects/Data/Tests/Sources/ChallengeRepositoryTests/Base/MockChallengeService.swift
  HMH_Tuist_iOS/Projects/Data/Tests/Sources/ChallengeRepositoryTests/GetSuccesChallengeTest/GetSuccesChallengeTest.swift
  HMH_Tuist_iOS/Projects/Domain/Sources/Entity/Challenge/ChallengeDetail.swift
  HMH_Tuist_iOS/Projects/Domain/Sources/Entity/Challenge/ChallengeSuccessInfo.swift
  HMH_Tuist_iOS/Projects/Domain/Sources/Entity/Point/PointDetail.swift
  HMH_Tuist_iOS/Projects/Domain/Sources/Entity/Point/PointStatusEnum.swift
  HMH_Tuist_iOS/Projects/Domain/Sources/RepositoryInterface/ChallengeRepositoryType.swift
  HMH_Tuist_iOS/Projects/Domain/Sources/Usecase/Challenge/ChallengeUseCase.swift
  HMH_Tuist_iOS/Projects/Domain/Sources/Usecase/Point/PointUseCase.swift
  HMH_Tuist_iOS/Projects/Features/ChallengeFeature/Demo/Sources/ChallengeFeatureApp.swift
  HMH_Tuist_iOS/Projects/Features/ChallengeFeature/Demo/Sources/Example.swift
  HMH_Tuist_iOS/Projects/Features/ChallengeFeature/Sources/ViewModels/ChallengeViewModel.swift
  HMH_Tuist_iOS/Projects/Features/ChallengeFeature/Sources/ViewModels/PointViewModel.swift
  HMH_Tuist_iOS/Projects/Features/ChallengeFeature/Sources/Views/ChallengeAppListView.swift
  HMH_Tuist_iOS/Projects/Features/ChallengeFeature/Sources/Views/ChallengeView.swift
  HMH_Tuist_iOS/Projects/Features/ChallengeFeature/Sources/Views/PointView.swift
  HMH_Tuist_iOS/Projects/Modules/DSKit/Sources/Calendar/AchievementStatusType.swift
  HMH_Tuist_iOS/Projects/Modules/DSKit/Sources/Calendar/HMHCalendar.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/DTO/Challenge/ChallengeSuccessDTO.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Service/Challenge/ChallengeAPI.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Sources/Service/Challenge/ChallengeService.swift
  HMH_Tuist_iOS/Projects/Modules/Networks/Tests/Sources/Service/ChallengeServiceTests.swift
Labels: 🐰지희, ✨FEAT
