Repository Team-HMH/HMH_iOS, pull requests merged in 2024-05, with the labels that each got.

#11 Feat [#5] 커스텀 네비게이션바 제작
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Assets.xcassets/navigationPoint.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/navigationPoint.imageset/ic-1.png
  HMH_iOS/HMH_iOS/Assets.xcassets/navigationPoint.imageset/ic-1@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/navigationPoint.imageset/ic-1@3x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/pointCount.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/pointCount.imageset/Point.png
  HMH_iOS/HMH_iOS/Assets.xcassets/pointCount.imageset/Point@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/pointCount.imageset/Point@3x.png
  HMH_iOS/HMH_iOS/Global/Resource/String.swift
  HMH_iOS/HMH_iOS/Global/Struct/CustomNavigationBarModifier.swift
  HMH_iOS/HMH_iOS/Presentation/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/HomeView.swift
  HMH_iOS/HMH_iOS/Presentation/MyPageView.swift
  HMH_iOS/HMH_iOS/Presentation/NavigationBarView.swift
Labels: 🐰지희, 🎨STYLE

#22 Feat [#19] Login view 구현
  .gitignore
  HMH_iOS/HMH-iOS-Info.plist
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMH_iOS/HMH_iOS/Assets.xcassets/appleLogo.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/appleLogo.imageset/ic_baseline-apple.png
  HMH_iOS/HMH_iOS/Assets.xcassets/appleLogo.imageset/ic_baseline-apple@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/appleLogo.imageset/ic_baseline-apple@3x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/kakaoLogo.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/kakaoLogo.imageset/ri_kakao-talk-fill.png
  HMH_iOS/HMH_iOS/Assets.xcassets/kakaoLogo.imageset/ri_kakao-talk-fill@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/kakaoLogo.imageset/ri_kakao-talk-fill@3x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/yelloBtn.colorset/Contents.json
  HMH_iOS/HMH_iOS/Global/HMH_iOSApp.swift
  HMH_iOS/HMH_iOS/Global/Resource/String.swift
  HMH_iOS/HMH_iOS/Presentation/Login/LoginView.swift
  HMH_iOS/HMH_iOS/Presentation/Login/Models/SocialLoginModel.swift
  HMH_iOS/HMH_iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Login/Views/LoginButton.swift
  HMH_iOS/HMH_iOS/Presentation/Login/Views/SwipeView.swift
  HMH_iOS/HMH_iOS/Presentation/TabBarView.swift
Labels: 😎선우, ✨FEAT, 🎨STYLE, ⚙️SET

#24 Feat [#23] SplashView UI 구현
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Assets.xcassets/AppIcon.appiconset/1024 1.png
  HMH_iOS/HMH_iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/AppIcon.appiconset/appLogo.png
  HMH_iOS/HMH_iOS/Assets.xcassets/OnboardingSecond.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/OnboardingSecond.imageset/OnboardingSecond.png
  HMH_iOS/HMH_iOS/Assets.xcassets/OnboardingSecond.imageset/OnboardingSecond@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/OnboardingSecond.imageset/OnnoardingSecond.png
  HMH_iOS/HMH_iOS/Assets.xcassets/OnboardingSecond.imageset/OnnoardingSecond@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/OnboardingSecond.imageset/OnnoardingSecond@3x.png
  HMH_iOS/HMH_iOS/Global/Resource/Lottie/Logo_wordmark_white.json
  HMH_iOS/HMH_iOS/Global/Resource/Lottie/Splash_Bg.json
  HMH_iOS/HMH_iOS/Presentation/Login/LoginView.swift
  HMH_iOS/HMH_iOS/Presentation/SplashView.swift
Labels: 😎선우, ✨FEAT, 🔧FIX

#27 [Set/#26] 네트워크 계층 세팅
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMH_iOS/HMH_iOS/Network/Base/AuthInterceptor.swift
  HMH_iOS/HMH_iOS/Network/Base/BaseModel.swift
  HMH_iOS/HMH_iOS/Network/Base/BaseTargetType.swift
  HMH_iOS/HMH_iOS/Network/Base/NetworkProvider.swift
  HMH_iOS/HMH_iOS/Network/DTO/Auth/RefreshTokenResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Auth/SignUpRequestDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Auth/SignUpResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Auth/SocialLoginRequestDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Auth/SocialLoginResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/AddAppRequestDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/AddAppResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/CreateChallengeRequestDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/CreateChallengeResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/DeleteAppRequestDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/EmptyResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/GetChallengeResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/GetHomeChallengeResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/HomeChallengeResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/MidnightRequestDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/MyPage/GetUserDataResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/Foundation/APIConstants.swift
  HMH_iOS/HMH_iOS/Network/Foundation/Config.swift
  HMH_iOS/HMH_iOS/Network/Foundation/MoyaLoggerPlugin.swift
  HMH_iOS/HMH_iOS/Network/Foundation/NetworkHelper.swift
  HMH_iOS/HMH_iOS/Network/Foundation/NetworkResult.swift
  HMH_iOS/HMH_iOS/Network/Foundation/ResponseData.swift
  HMH_iOS/HMH_iOS/Network/Router/AuthRouter.swift
  HMH_iOS/HMH_iOS/Network/Router/ChallengeRouter.swift
  HMH_iOS/HMH_iOS/Network/Router/MyPageRouter.swift
  HMH_iOS/HMH_iOS/Network/Service/Providers.swift
Labels: 🐰지희, ⚙️SET

#28 [Feat/#21] 챌린지뷰 구현 및 스크린타임 API 연결
  HMH_iOS/HMHDeviceActivityReport/ActivityModel.swift
  HMH_iOS/HMHDeviceActivityReport/AppActivityReport.swift
  HMH_iOS/HMHDeviceActivityReport/AppActivityView.swift
  HMH_iOS/HMHDeviceActivityReport/HMHDeviceActivityReport.swift
  HMH_iOS/HMHDeviceActivityReport/TotalActivityReport.swift
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Assets.xcassets/ChallengeBackground.imageset/ChallengeBackground.png
  HMH_iOS/HMH_iOS/Assets.xcassets/ChallengeBackground.imageset/ChallengeBackground@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/ChallengeBackground.imageset/ChallengeBackground@3x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/ChallengeBackground.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/addAppButton.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/addAppButton.imageset/addAppButton.png
  HMH_iOS/HMH_iOS/Assets.xcassets/addAppButton.imageset/addAppButton@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/addAppButton.imageset/addAppButton@3x.png
  HMH_iOS/HMH_iOS/Global/Resource/String.swift
  HMH_iOS/HMH_iOS/Global/Struct/CustomNavigationBarModifier.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ChallengeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/PointViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ScreenTimeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeAppListView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/PointView.swift
  HMH_iOS/HMH_iOS/Presentation/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Home/ViewModels/HomeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Views/HomeView.swift
  HMH_iOS/HMH_iOS/Presentation/NavigationBarView.swift
  HMH_iOS/HMH_iOS/Presentation/TabBarView.swift
Labels: 🐰지희, ✨FEAT

#29 Feat [#25] 커스텀 팝업 구현
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Resource/String.swift
  HMH_iOS/HMH_iOS/Global/Struct/CustomAlertModifier.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Alert/ChallengeCreationCompleteAlertView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Alert/InsufficientPointsAlertView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Alert/LogoutAlertView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Alert/UnlockAlertVIew.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Alert/UnlockCompleteAlertView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Alert/UsePointsAlertView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Alert/WithdrawAlertView.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/Views/MyPageButton.swift
  HMH_iOS/HMH_iOS/Presentation/MyPageView.swift
Labels: 😎선우, ✨FEAT, 🎨STYLE

#31 Network [#25] Login & Onboarding 네트워크 연결
  HMH_iOS/HMH-iOS-Info.plist
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/HMH_iOSApp.swift
  HMH_iOS/HMH_iOS/Network/Base/AuthInterceptor.swift
  HMH_iOS/HMH_iOS/Network/Base/NetworkProvider.swift
  HMH_iOS/HMH_iOS/Network/Foundation/APIConstants.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Manager/UserManager.swift
  HMH_iOS/HMH_iOS/Presentation/Login/LoginView.swift
  HMH_iOS/HMH_iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/MyPageView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/NextButtonView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/SurveyButton.swift
  HMH_iOS/HMH_iOS/Presentation/SplashView.swift
Labels: 😎선우, 📡NETWORK

#37 Feat [#36] 챌린지 생성 기능 추가
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMH_iOS/HMH_iOS/Global/HMH_iOSApp.swift
  HMH_iOS/HMH_iOS/Network/Base/AuthInterceptor.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/CreateChallengeResponseDTO.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Manager/UserManager.swift
  HMH_iOS/HMH_iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/MyPageView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingContentView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/StoryContentView.swift
Labels: 😎선우, ✨FEAT, 📡NETWORK

#38 Network [#34] 챌린지뷰 Realm 적용 / 번들 아이디 가져오기 시도 중
  HMH_iOS/DeviceActivityMonitor/DeviceActivityMonitorExtension.swift
  HMH_iOS/HMHDeviceActivityReport/AppActivityReport.swift
  HMH_iOS/HMHDeviceActivityReport/ChallengeActivityView.swift
  HMH_iOS/HMHDeviceActivityReport/RealmManager.swift
  HMH_iOS/HMHDeviceActivityReport/TotalActivityReport.swift
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  HMH_iOS/HMH_iOS/Assets.xcassets/AppIcon.appiconset/Contents.json
  HMH_iOS/HMH_iOS/Global/Application/AppDelegate.swift
  HMH_iOS/HMH_iOS/Global/Application/MidnightTaskScheduler.swift
  HMH_iOS/HMH_iOS/Global/DataModel/DailyChallengeModel.swift
  HMH_iOS/HMH_iOS/Global/Manager/AppStorageKey.swift
  HMH_iOS/HMH_iOS/Global/Resource/String.swift
  HMH_iOS/HMH_iOS/Global/Struct/CustomButtonModifer.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ChallengeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ScreenTimeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/PointView.swift
  HMH_iOS/HMH_iOS/Presentation/NavigationBarView.swift
Labels: 🐰지희, ✨FEAT, 📡NETWORK

#41 Feat [#39] challenge 부분 UI 및 분기처리 추가
  HMH_iOS/HMH_iOS/Assets.xcassets/chevronDown.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/chevronDown.imageset/chevron-down.png
  HMH_iOS/HMH_iOS/Assets.xcassets/chevronDown.imageset/chevron-down@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/chevronDown.imageset/chevron-down@3x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/chevronUp.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/chevronUp.imageset/chevron-down.png
  HMH_iOS/HMH_iOS/Assets.xcassets/chevronUp.imageset/chevron-down@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/chevronUp.imageset/chevron-down@3x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/failStar.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/failStar.imageset/Property 1=회색.png
  HMH_iOS/HMH_iOS/Assets.xcassets/failStar.imageset/Property 1=회색@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/failStar.imageset/Property 1=회색@3x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/successStar.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/successStar.imageset/Property 1=Default.png
  HMH_iOS/HMH_iOS/Assets.xcassets/successStar.imageset/Property 1=Default@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/successStar.imageset/Property 1=Default@3x.png
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/GetChallengeResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/HomeChallengeResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/Router/ChallengeRouter.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ChallengeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ScreenTimeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/StoryContentView.swift
Labels: 😎선우, ✨FEAT

#46 Network [#43] point 네트워크 구현, 토스트 메세지
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Assets.xcassets/toast.colorset/Contents.json
  HMH_iOS/HMH_iOS/Global/Struct/CustomAlertModifier.swift
  HMH_iOS/HMH_iOS/Global/Struct/CustomNavigationBarModifier.swift
  HMH_iOS/HMH_iOS/Network/DTO/Point/EarnPointResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Point/PointListResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Point/PointRequestDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Point/UsagePointResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Point/UsePointResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Point/UserPointResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/Foundation/APIConstants.swift
  HMH_iOS/HMH_iOS/Network/Router/PointRouter.swift
  HMH_iOS/HMH_iOS/Network/Service/Providers.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/PointViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/PointView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Toast/HMHToastView.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Views/HomeView.swift
  HMH_iOS/HMH_iOS/Presentation/NavigationBarView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/GoalTimeView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingContentView.swift
Labels: 😎선우, 🎨STYLE, 📡NETWORK
