Repository Team-HMH/HMH_iOS, pull requests merged in 2024-06, with the labels that each got.

#48 Feat [#47] background schedule&FamilyPicker 연결
  HMH_iOS/HMH_iOS/Global/Application/MidnightTaskScheduler.swift
  HMH_iOS/HMH_iOS/Global/HMH_iOSApp.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ChallengeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ScreenTimeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Views/HomeView.swift
  HMH_iOS/HMH_iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingContentView.swift
Labels: 😎선우, ✨FEAT

#49 [Feat/#44] 로직 점검 및 앱 잠금 연결
  HMH_iOS/DeviceActivityMonitor/DeviceActivityMonitorExtension.swift
  HMH_iOS/HMH_iOS/Assets.xcassets/failStar.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/failStar.imageset/failStar.png
  HMH_iOS/HMH_iOS/Assets.xcassets/failStar.imageset/failStar@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/failStar.imageset/failStar@3x.png
  HMH_iOS/HMH_iOS/Global/Application/AppDelegate.swift
  HMH_iOS/HMH_iOS/Global/HMH_iOSApp.swift
  HMH_iOS/HMH_iOS/Global/Manager/NotificationManager.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ChallengeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/PointViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/PointView.swift
  HMH_iOS/HMH_iOS/Presentation/Home/ViewModels/HomeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Login/ViewModels/LoginViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
Labels: 🐰지희, ✨FEAT

#52 Feat [#50] Alert 부분 처리
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Assets.xcassets/remainEarnPoint.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/remainEarnPoint.imageset/Point.png
  HMH_iOS/HMH_iOS/Assets.xcassets/remainEarnPoint.imageset/Point@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/remainEarnPoint.imageset/Point@3x.png
  HMH_iOS/HMH_iOS/Global/HMH_iOSApp.swift
  HMH_iOS/HMH_iOS/Global/Manager/NotificationManager.swift
  HMH_iOS/HMH_iOS/Global/Resource/String.swift
  HMH_iOS/HMH_iOS/Global/Struct/CustomAlertModifier.swift
  HMH_iOS/HMH_iOS/Network/Base/NetworkProvider.swift
  HMH_iOS/HMH_iOS/Network/DTO/Point/GetEarnPointResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Point/PatchEarnPointResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Point/UsagePointResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/Router/PointRouter.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ChallengeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/PointViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Alert/UnlockAlertVIew.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Alert/UnlockCompleteAlertView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Alert/UsePointsAlertView.swift
  HMH_iOS/HMH_iOS/Presentation/ContentView.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/Views/ServicePrepareView.swift
  HMH_iOS/HMH_iOS/Presentation/MyPageView.swift
  HMH_iOS/HMH_iOS/Presentation/NavigationBarView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingContentView.swift
Labels: 😎선우, ✨FEAT, 📡NETWORK

#53 [Feat/#51] 스크린 타임 앱 잠금 관련 이슈 해결
  HMH_iOS/DeviceActivityMonitor/DeviceActivityMonitorExtension.swift
  HMH_iOS/HMH-iOS-Info.plist
  HMH_iOS/HMHDeviceActivityReport/AppActivityView.swift
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Application/AppDelegate.swift
  HMH_iOS/HMH_iOS/Global/Application/NetworkOperator.swift
  HMH_iOS/HMH_iOS/Global/DataModel/DailyChallengeModel.swift
  HMH_iOS/HMH_iOS/Global/Struct/CustomAlertModifier.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/MidnightRequestDTO.swift
  HMH_iOS/HMH_iOS/Network/Foundation/APIConstants.swift
  HMH_iOS/HMH_iOS/Network/Router/ChallengeRouter.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ChallengeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ScreenTimeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Home/ViewModels/HomeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingContentView.swift
Labels: 🐰지희, ✨FEAT

#55 Feat [#45] 성공 여부 저장 로직 추가
  HMH_iOS/DeviceActivityMonitor/DeviceActivityMonitorExtension.swift
  HMH_iOS/HMHDeviceActivityReport/TotalActivityReport.swift
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Assets.xcassets/shieldLock.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/shieldLock.imageset/shieldLock.png
  HMH_iOS/HMH_iOS/Assets.xcassets/shieldLock.imageset/shieldLock@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/shieldLock.imageset/shieldLock@3x.png
  HMH_iOS/HMH_iOS/Global/Application/AppDelegate.swift
  HMH_iOS/HMH_iOS/Global/Application/MidnightTaskScheduler.swift
  HMH_iOS/HMH_iOS/Global/Application/NetworkOperator.swift
  HMH_iOS/HMH_iOS/Global/DataModel/DailyChallengeModel.swift
  HMH_iOS/HMH_iOS/Global/DataModel/UserChallenge.xcdatamodeld/UserChallenge.xcdatamodel/contents
  HMH_iOS/HMH_iOS/Global/Extension/Date+.swift
  HMH_iOS/HMH_iOS/Global/Manager/NotificationManager.swift
  HMH_iOS/HMH_iOS/Global/Manager/UserDefaultsManager.swift
  HMH_iOS/HMH_iOS/Network/DTO/Challenge/HomeChallengeResponseDTO.swift
  HMH_iOS/HMH_iOS/Network/DTO/Point/PatchPointUseResponseDTO.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ChallengeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ScreenTimeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/ShieldConfigureExtension/ShieldConfigurationExtension.swift
Labels: 🐰지희, ✨FEAT

#57 [Fix/#56] 자체 QA 사항
  HMH_iOS/HMHDeviceActivityReport/AppActivityView.swift
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Assets.xcassets/doneStar.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/doneStar.imageset/doneStar.png
  HMH_iOS/HMH_iOS/Assets.xcassets/doneStar.imageset/doneStar@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/doneStar.imageset/doneStar@3x.png
  HMH_iOS/HMH_iOS/Network/DTO/Point/PatchEarnPointResponseDTO.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ChallengeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Custom/ContentView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Custom/PickerView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Custom/SplashView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Navigation/NavigationBarView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/TabBar/CustomTabView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/TabBar/TabBarView.swift
Labels: 🐰지희, ✨FEAT

#58 Fix [ #54] 중복 로그인 오류 해결
  HMH_iOS/HMH_iOS/Global/Resource/String.swift
  HMH_iOS/HMH_iOS/Network/Foundation/APIConstants.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Manager/UserManager.swift
  HMH_iOS/HMH_iOS/Presentation/MyPage/ViewModels/MyPageViewModel.swift
Labels: 😎선우, 🔧FIX

#60 Refactor [#59] v 1.0.0 심사 대응
  HMH_iOS/HMHDeviceActivityReport/ActivityModel.swift
  HMH_iOS/HMHDeviceActivityReport/AppActivityReport.swift
  HMH_iOS/HMHDeviceActivityReport/AppActivityView.swift
  HMH_iOS/HMHDeviceActivityReport/ChallengeActivityView.swift
  HMH_iOS/HMHDeviceActivityReport/ChallengeDeviceActivityReportScene.swift
  HMH_iOS/HMHDeviceActivityReport/HomeDeviceActivityReportScene.swift
  HMH_iOS/HMHDeviceActivityReport/TotalActivityReport.swift
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Global/Manager/AppStorageKey.swift
  HMH_iOS/HMH_iOS/Global/Manager/NotificationManager.swift
  HMH_iOS/HMH_iOS/Global/Resource/String.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ChallengeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/PointViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ScreenTimeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/PointView.swift
  HMH_iOS/HMH_iOS/Presentation/Home/ViewModels/HomeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Views/HomeView.swift
  HMH_iOS/HMH_iOS/Presentation/Login/LoginView.swift
  HMH_iOS/HMH_iOS/Presentation/Login/Views/SwipeView.swift
Labels: 🐰지희, 🔧FIX
