Repository Team-HMH/HMH_iOS, pull requests merged in 2024-07, with the labels that each got.

#62 Refactor [#61] 온보딩 QA 반영
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/MyPageView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/AppGoalTimeView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/GoalTimeView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingContentView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/SurveyButton.swift
Labels: 😎선우, 🌿 REFACTOR

#67 Set [#66] 개발 서버, 상용 서버 분리 작업
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Assets.xcassets/AppIcon_dev.appiconset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/AppIcon_dev.appiconset/devicon.png
Labels: 🐰지희, ⚙️SET

#69 Set [#68] API 마이그레이션을 위한 path 수정
  HMH_iOS/HMH_iOS/Network/Router/AuthRouter.swift
  HMH_iOS/HMH_iOS/Network/Router/ChallengeRouter.swift
  HMH_iOS/HMH_iOS/Network/Router/MyPageRouter.swift
  HMH_iOS/HMH_iOS/Network/Router/PointRouter.swift
Labels: 🐰지희, ⚙️SET

#72 Fix [#71] onboarding 수정 사항 반영
  HMH_iOS/HMH_iOS/Global/Resource/String.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/Views/OnboardingContentView.swift
Labels: 😎선우, 🔧FIX

#74 Feat [#70] 기획 변경 사항 적용
  HMH_iOS/HMHDeviceActivityReport/AppActivityView.swift
  HMH_iOS/HMHDeviceActivityReport/ChallengeActivityView.swift
  HMH_iOS/HMHDeviceActivityReport/HomeDeviceActivityReportScene.swift
  HMH_iOS/HMHDeviceActivityReport/TotalActivityReport.swift
  HMH_iOS/HMH_iOS.xcodeproj/project.pbxproj
  HMH_iOS/HMH_iOS/Assets.xcassets/addAppButton.imageset/addAppButton.png
  HMH_iOS/HMH_iOS/Assets.xcassets/addAppButton.imageset/addAppButton@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/addAppButton.imageset/addAppButton@3x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/appAddBtn.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/appAddBtn.imageset/appAddBtn.png
  HMH_iOS/HMH_iOS/Assets.xcassets/appAddBtn.imageset/appAddBtn@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/appAddBtn.imageset/appAddBtn@3x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/guideImg1.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/guideImg1.imageset/guideImg1.png
  HMH_iOS/HMH_iOS/Assets.xcassets/guideImg1.imageset/guideImg1@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/guideImg1.imageset/guideImg1@3x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/guideImg2.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/guideImg2.imageset/guideImage2.png
  HMH_iOS/HMH_iOS/Assets.xcassets/guideImg2.imageset/guideImage2@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/guideImg2.imageset/guideImage2@3x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/guideImg3.imageset/Contents.json
  HMH_iOS/HMH_iOS/Assets.xcassets/guideImg3.imageset/guideImg3.png
  HMH_iOS/HMH_iOS/Assets.xcassets/guideImg3.imageset/guideImg3@2x.png
  HMH_iOS/HMH_iOS/Assets.xcassets/guideImg3.imageset/guideImg3@3x.png
  HMH_iOS/HMH_iOS/Global/Application/AppDelegate.swift
  HMH_iOS/HMH_iOS/Global/Manager/NotificationManager.swift
  HMH_iOS/HMH_iOS/Global/Resource/String.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/ViewModels/ChallengeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeHeaderView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/ChallengeView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/EmptyHeaderView.swift
  HMH_iOS/HMH_iOS/Presentation/Challenge/Views/PointView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Custom/ContentView.swift
  HMH_iOS/HMH_iOS/Presentation/Common/Manager/UserManager.swift
  HMH_iOS/HMH_iOS/Presentation/Home/ViewModels/HomeViewModel.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Views/GuideView.swift
  HMH_iOS/HMH_iOS/Presentation/Home/Views/HomeView.swift
  HMH_iOS/HMH_iOS/Presentation/Onboarding/ViewModels/OnboardingViewModel.swift
Labels: 🐰지희, ✨FEAT
